Repository solop-develop/frontend-default-theme, pull requests merged in 2022-12, with the labels that each got.

#412 fix: Callout set context values.
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/TabPanel.vue
  components/ADempiere/TabManager/convenienceButtons.vue
Labels: bug, (REC) Records, (WIN) Windows

#413 Fix: Add References to Tab Info
  components/ADempiere/PanelInfo/Component/ReferenceRecords/index.vue
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#409 feat: Delete Attachment.
  components/ADempiere/Attachment/index.vue
  components/ADempiere/Form/BarcodeReader/index.vue
  components/ADempiere/Form/VPOS/Order/line/infoOrderLine/imageProduct.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
  components/ADempiere/PanelInfo/Component/RecordNotes/index.vue
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (WIN) Windows

#414 POS: Suport shipment previwer
  components/ADempiere/Form/VPOS/Collection/index.vue
  components/ADempiere/Form/VPOS/ConfirmDelivery/index.vue
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/Order/line/infoOrderLine/index.vue
Labels: (POS) Point Of Sales, (FRM) Form

#416 Fix: Add option next and previous
  components/ADempiere/DataTable/Components/CustomPagination.vue
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/TabPanel.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#423 feat: Upload valid attachment.
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (WIN) Windows

#421 Fix: POS Print Ticket and preview order when reversing
  components/ADempiere/Form/VPOS/Options/index.vue
Labels: enhancement, (POS) Point Of Sales, (FRM) Form

#422 Support to the Print/Export Payment Form
  components/ADempiere/Form/VPayPrint/index.vue
  components/ADempiere/Form/index.vue
Labels: enhancement, (FRM) Form

#424 Fix: Improve Workflow Activity Viewer
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/index.vue
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/WorkflowDiagram/index.vue
Labels: (WFL) Workflows, (UX) User Experience

#426 feat: Percentage Progress Column.
  components/ADempiere/ContainerOptions/ProgressPercentage.vue
  components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  components/ADempiere/DataTable/Windows/index.vue
Labels: enhancement, (WIN) Windows, (ULP) UI Lookups, (UX) User Experience

#425 Fix: Add Scroll in the full window
  components/ADempiere/ContainerOptions/FullScreenContainer/useFullScreenContainer.js
  components/ADempiere/PanelDefinition/StandardPanel.vue
  components/ADempiere/TabManager/TabPanel.vue
  components/ADempiere/TabManager/index.vue
  components/ADempiere/TabManager/tabChild.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#427 fix: Change percentage progress color to blue.
  components/ADempiere/ContainerOptions/ProgressPercentage.vue
Labels: enhancement, (UX) User Experience

#431 Fix: Support Exists References
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (UX) User Experience

#434 feat: Add show/hidden table columns.
  components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/TabPanel.vue
  components/ADempiere/TabManager/index.vue
Labels: (WIN) Windows, (UX) User Experience

#436 fix: Window style.
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/PanelDefinition/StandardPanel.vue
  components/ADempiere/TabManager/convenienceButtons.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#435 feat: Add copy to clipboard Value and DocumentNo.
  components/ADempiere/FieldDefinition/FieldText.vue
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#433 Support form VPrint
  components/ADempiere/Form/VPOS/ProductInfo/index.vue
  components/ADempiere/Form/VPayPrint/index.vue
  components/ADempiere/PanelInfo/index.vue
Labels: enhancement, (FRM) Form
