Repository solop-develop/frontend-default-theme, pull requests merged in 2022-09, with the labels that each got.

#283 POS Remove validation of add payment
  components/ADempiere/Form/VPOS/Collection/index.vue
Labels: wontfix, (POS) Point Of Sales

#284 feat: Account Finder with many Columns
  components/ADempiere/DataTable/Components/CellInfo.vue
  components/ADempiere/FieldDefinition/FieldAccount/panel.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
Labels: wontfix, (FM) Form

#285 POS Fixed Quantity PIN
  components/ADempiere/Form/VPOS/Collection/overdrawnInvoice/index.vue
  components/ADempiere/Form/VPOS/Options/Cashwithdrawal/index.vue
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/Order/line/index.vue
  components/ADempiere/Form/VPOS/Order/orderLineMixin.js
  components/ADempiere/Form/VPOS/posMixin.js
Labels: bug, (POS) Point Of Sales

#286 fix: Select Business Partner in Sales Order
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/mixinBusinessPartner.js
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
Labels: bug, (FM) Form, (REC) Records, (WIN) Windows

#287 fix: Load records on tab childs.
  components/ADempiere/TabManager/tabChild.vue
Labels: bug, (REC) Records, (WIN) Windows

#288 fix: Duplicated request tab entities.
  components/ADempiere/TabManager/index.vue
  components/ADempiere/TabManager/tabChild.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#290 feat: Set accounting combination values
  components/ADempiere/FieldDefinition/FieldAccountingCombination/buttonToList.vue
  components/ADempiere/FieldDefinition/FieldAccountingCombination/fieldsList.js
  components/ADempiere/FieldDefinition/FieldAccountingCombination/index.vue
  components/ADempiere/FieldDefinition/FieldAccountingCombination/mixinAccountingCombination.js
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
Labels: bug, (FM) Form

#292 fix: Displayed value on search field forms.
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: bug, (FM) Form, (REC) Records

#293 fixed: Accouting Combination set values selected on query criteria.
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
Labels: enhancement, (FRM) Form, (ULP) UI Lookups

#294 Fix: Set accounting combination to save value on window
  components/ADempiere/FieldDefinition/FieldAccountingCombination/mixinAccountingCombination.js
Labels: (REC) Records, (WIN) Windows

#295 Fix: Change Field Accounting Combination
  components/ADempiere/FieldDefinition/FieldAccountingCombination/index.vue
  components/ADempiere/FieldDefinition/FieldAccountingCombination/mixinAccountingCombination.js
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
Labels: bug, (FRM) Form, (ULP) UI Lookups

#296 POS Support to edit order line in mobile mode
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/Order/line/editLineMobile.vue
  components/ADempiere/Form/VPOS/templateDevice/desktop.vue
Labels: enhancement, (POS) Point Of Sales

#297 Revert "POS Support to edit order line in mobile mode"
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/Order/line/editLineMobile.vue
  components/ADempiere/Form/VPOS/templateDevice/desktop.vue
Labels: wontfix, (POS) Point Of Sales

#298 feat: POS Support to edit order line in mobile mode.
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/Order/line/editLineMobile.vue
  components/ADempiere/Form/VPOS/templateDevice/desktop.vue
Labels: enhancement, (POS) Point Of Sales, (FRM) Form

#300 feat: POS Add empty translations.
  components/ADempiere/Form/VPOS/BusinessPartner/businessPartnerUpdate.vue
  components/ADempiere/Form/VPOS/BusinessPartner/shippingAddressFieldLocation/fieldsList.js~HEAD
  components/ADempiere/Form/VPOS/BusinessPartner/shippingAddressFieldLocation/fieldsList.js~develop
  components/ADempiere/Form/VPOS/Collection/overdrawnInvoice/index.vue
  components/ADempiere/Form/VPOS/Options/AssignSeller/index.vue
  components/ADempiere/Form/VPOS/Options/CashOpening/index.vue
  components/ADempiere/Form/VPOS/Options/CashSummaryMovements/index.vue
  components/ADempiere/Form/VPOS/Options/Cashwithdrawal/index.vue
  components/ADempiere/Form/VPOS/Options/index.vue
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/Order/line/index.vue
  components/ADempiere/Form/VPOS/OrderList/FindOrders/index.vue
  components/ADempiere/Form/VPOS/posMixin.js
Labels: enhancement, (POS) Point Of Sales, (TRL) Translation

#301 fix: POS Message pin validate successfully unnecessary.
  components/ADempiere/Form/VPOS/Options/AssignSeller/index.vue
  components/ADempiere/Form/VPOS/Options/CashOpening/index.vue
  components/ADempiere/Form/VPOS/Options/CashSummaryMovements/index.vue
  components/ADempiere/Form/VPOS/Options/Cashwithdrawal/index.vue
  components/ADempiere/Form/VPOS/Options/index.vue
Labels: bug, (POS) Point Of Sales

#302 Fix: Size View Table
  components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (UIX) User Experience

#303 fix: Field select empty values with string.
  components/ADempiere/FieldDefinition/mixin/mixinField.js
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#305 feat: Separate cell edit and cell display.
  components/ADempiere/DataTable/Browser/index.vue
  components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  components/ADempiere/DataTable/Components/CellEditInfo.vue
  components/ADempiere/DataTable/Components/CellInfo.vue
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
Labels: enhancement, (REC) Records, (SB) Smart Browser, (WIN) Windows, (CIO) Code Improvement or Optimization

#306 fixed: SB Field Search query criteria.
  components/ADempiere/FieldDefinition/FieldAccountingCombination/mixinAccountingCombination.js
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/mixinBusinessPartner.js
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
  components/ADempiere/FieldDefinition/mixin/mixinField.js
  components/ADempiere/FieldDefinition/useFieldDefinition.js
Labels: bug, (FRM) Form, (REC) Records, (SB) Smart Browser, (ULP) UI Lookups

#308 Fix: Support Accounting
  components/ADempiere/PanelInfo/Component/Accounting/fieldsList.js
  components/ADempiere/PanelInfo/Component/Accounting/heardList.js
  components/ADempiere/PanelInfo/Component/Accounting/index.vue
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (WIN) Windows

#310 fix: Loading RePost.
  components/ADempiere/PanelInfo/Component/Accounting/fieldsList.js
  components/ADempiere/PanelInfo/Component/Accounting/index.vue
Labels: bug, (WIN) Windows

#311 Fix: Support Button Save
  components/ADempiere/TabManager/convenienceButtons.vue
Labels: bug, (REC) Records, (WIN) Windows, (UX) User Experience
