Repository solop-develop/frontend-default-theme, pull requests merged in 2022-05, with the labels that each got.

#1 fix: Field zoom to window.
  api/ADempiere/field/locator.js
  api/ADempiere/user-interface/persistence.js
  components/ADempiere/TabManager/index.vue
Labels: bug

#15 keep the type of report when changing the print format
  components/ADempiere/ActionMenu/Actions.vue
  components/ADempiere/ActionMenu/index.vue
  components/ADempiere/TabManager/index.vue
Labels: bug

#16 Add download option to pdf files
  components/ADempiere/ActionMenu/Actions.vue
  components/ADempiere/FileRender/PdfFile/index.vue
  components/ADempiere/ModalDialog/index.vue
Labels: enhancement

#19 feat: Generated report with last parameters.
  components/ADempiere/ActionMenu/Actions.vue
  components/ADempiere/ActionMenu/index.vue
  components/ADempiere/FileRender/PdfFile/index.vue
  components/ADempiere/FileRender/downloadFile.vue
  router/modules/ADempiere/staticRoutes.js
Labels: bug, enhancement

#20 Support Print Window
  componentes/Adempiere/ModalDialog/index.vue
  components/ADempiere/FileRender/PdfFile/index.vue
Labels: enhancement

#21 feat: Displayed report associated in button field.
  components/ADempiere/ActionMenu/Actions.vue
Labels: enhancement

#22 isLoading Data Table
  components/ADempiere/DefaultTable/index.vue
Labels: bug, enhancement

#23 feat: Add open Smart Browser associated.
  components/ADempiere/ActionMenu/Actions.vue
Labels: enhancement

#24 Support Current Page
  components/ADempiere/DefaultTable/CustomPagination.vue
  components/ADempiere/DefaultTable/index.vue
  components/ADempiere/Form/VPOS/OrderList/FindOrders/index.vue
  components/ADempiere/Form/VPOS/OrderList/fastOrder.vue
  components/ADempiere/Form/VPOS/OrderList/searchCompleteOrders.vue
  components/ADempiere/Form/VPOS/OrderList/toDeliver.vue
Labels: enhancement

#25 feat: Add button process.
  components/ADempiere/Field/FieldButton.vue
  components/ADempiere/Field/FieldOptions/index.vue
  components/ADempiere/Field/index.vue
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
Labels: enhancement
