Repository solop-develop/frontend-default-theme, pull requests merged in 2023-02, with the labels that each got.

#503 feat: Loading save sequence.
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
  components/ADempiere/PanelDefinition/DraggablePanel.vue
Labels: enhancement, (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows

#507 Fix: Validate Edit/Delete Comments
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
Labels: bug, (FRM) Form, (WIN) Windows, (SE) Security

#508 fix: Add date next action.
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/Form/Issues/index.vue
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
  components/ADempiere/TabManager/index.vue
Labels: bug

#511 fix: Set tree record out of table list
  components/ADempiere/PanelDefinition/TreePanel.vue
Labels: (REC) Records, (WIN) Windows, (UX) User Experience

#510 Fix: Support to Next Action Date and Expiration Type
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/Form/Issues/index.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
Labels: enhancement, (FRM) Form, (WIN) Windows

#512 feat: Zoom in from workflow
  components/ADempiere/Form/WorkflowActivity/index.vue
Labels: enhancement, (FRM) Form, (WFL) Workflows

#513 fix: Delete selection records displayed value on confirm.
  components/ADempiere/TabManager/convenienceButtons/index.vue
Labels: bug, (REC) Records, (WIN) Windows

#515 fix: Set value on field value on table.
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/button.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
Labels: bug, (FRM) Form

#514 Fix: Field Search Handle Change Size Page
  components/ADempiere/DataTable/Components/IndexColumn.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
Labels: bug, (FRM) Form, (REC) Records, (ULP) UI Lookups

#516 fix: Fix duplicated requests with activity notification.
  components/ADempiere/HeaderNotification/index.vue
Labels: bug, (CIO) Code Improvement or Optimization

#519 fix: Location Address form.
  components/ADempiere/FieldDefinition/FieldLocationAddress/fieldsList.js
  components/ADempiere/FieldDefinition/FieldLocationAddress/index.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/mixinLocationAddress.js
Labels: bug, (FRM) Form, (ULP) UI Lookups

#518 Support Mode Mobile
  components/ADempiere/Form/WorkflowActivity/index.vue
Labels: bug, (FRM) Form, (WFL) Workflows

#522 fix: Zoom from purchase window.
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
Labels: bug, (FRM) Form, (ULP) UI Lookups

#523 Fix Add Fields not visible in tree mode
  components/ADempiere/PanelDefinition/TreePanel.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
Labels: bug, (WIN) Windows

#525 fix: Display Column on Form.
  components/ADempiere/FieldDefinition/FieldSelect.vue
Labels: bug, (FRM) Form, (ULP) UI Lookups

#526 fix: Stored Displayed Value on select list.
  components/ADempiere/FieldDefinition/FieldDate.vue
  components/ADempiere/FieldDefinition/FieldNumber.vue
  components/ADempiere/FieldDefinition/FieldSelect.vue
Labels: bug, (ULP) UI Lookups

#529 fix: Displayed Value on lookups.
  components/ADempiere/FieldDefinition/FieldSelect.vue
Labels: bug, (ULP) UI Lookups

#528 Fix: Zoom from Issues window to All Requests or Request Window
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/Form/Issues/index.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
Labels: enhancement, (FRM) Form, (WIN) Windows

#530 fix: Clear search and requery with filters.
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (REC) Records, (WIN) Windows

#531 fix: Zoom reference window.
  components/ADempiere/PanelInfo/Component/ReferenceRecords/index.vue
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (REC) Records, (WIN) Windows

#532 feat: Add refresh lookup.
  components/ADempiere/FieldDefinition/FieldOptions/EmptyOption.vue
  components/ADempiere/FieldDefinition/FieldOptions/fieldOptionsList.js
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
  components/ADempiere/RightPanel/index.vue
Labels: enhancement, (ULP) UI Lookups

#533 fix: Run document action with field option.
  components/ADempiere/FieldDefinition/FieldOptions/DocumentStatus/index.vue
  components/ADempiere/TabManager/convenienceButtons/documentAction.vue
Labels: enhancement, (WFL) Workflows, (ULP) UI Lookups

#534 fix: Window filters.
  components/ADempiere/FieldDefinition/FieldOptions/fieldOptionsList.js
  components/ADempiere/TabManager/index.vue
Labels: (REC) Records, (WIN) Windows

#535 fix: Save Attribute Set Instance.
  components/ADempiere/FieldDefinition/FieldProductAttribute/detailAttributeInstance.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/index.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/listAttributeInstance.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/listTable.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/panelProductAttribute.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/useProductAttribute.js
Labels: bug, (FRM) Form, (ULP) UI Lookups

#536 fix: Remove redundant DisplayedValue.
  components/ADempiere/FieldDefinition/FieldAccountingCombination/buttonToList.vue
  components/ADempiere/FieldDefinition/FieldAccountingCombination/fieldsList.js
  components/ADempiere/FieldDefinition/FieldAccountingCombination/index.vue
  components/ADempiere/FieldDefinition/FieldAccountingCombination/mixinAccountingCombination.js
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
  components/ADempiere/FieldDefinition/FieldAutocomplete.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/index.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  components/ADempiere/FieldDefinition/FieldNumber.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/mixin/mixinField.js
  components/ADempiere/FieldDefinition/mixin/mixnWithDisplayColumn.js
Labels: enhancement, (FRM) Form, (ULP) UI Lookups

#537 fix: Create location.
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
  components/ADempiere/FieldDefinition/mixin/mixnWithDisplayColumn.js
Labels: bug, (FRM) Form, (ULP) UI Lookups

#538 feat: Add zoom custom lookups.
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/mixin/mixinField.js
  components/ADempiere/FieldDefinition/mixin/mixnWithDisplayColumn.js
Labels: enhancement, (FRM) Form, (ULP) UI Lookups

#539 feat: Warehouse Locator Field.
  components/ADempiere/FieldDefinition/FieldLocator.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/index.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/API-COMPOSITION.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/button.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/index.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/list.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/useLocatorWarehouse.js
  components/ADempiere/FieldDefinition/mixin/mixinField.js
  components/ADempiere/FieldDefinition/mixin/mixnWithDisplayColumn.js
  components/ADempiere/FieldDefinition/useDisplayedColumn.js
  components/ADempiere/FieldDefinition/useFieldDefinition.js
Labels: enhancement, (FRM) Form, (ULP) UI Lookups

#541 feat: Add filter columns on Smart Browser Table.
  components/ADempiere/DataTable/Browser/index.vue
  components/ADempiere/DataTable/Components/ColumnsDisplayOption.vue
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/TabPanel.vue
Labels: enhancement, (SB) Smart Browser

#544 feat: Move searchs field.
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/buttonBusinessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/mixinBusinessPartner.js
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/button.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
  components/ADempiere/Form/BarcodeReader/index.vue
Labels: (FRM) Form, (ULP) UI Lookups

#546 feat: Add search value on product attribute set instances list.
  components/ADempiere/FieldDefinition/FieldProductAttribute/detailAttributeInstance.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/index.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/listAttributeInstance.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
Labels: enhancement, (REC) Records, (ULP) UI Lookups

#547 fix: Table style after open any window.
  components/ADempiere/DataTable/Browser/index.vue
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/DataTable/index.vue
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  components/ADempiere/FieldDefinition/mixin/mixinField.js
Labels: bug, (FRM) Form, (REC) Records, (SB) Smart Browser, (WIN) Windows, (UX) User Experience

#548 fix: Mandatory columns available to hidden.
  components/ADempiere/DataTable/Browser/index.vue
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/TabManager/TabPanel.vue
  components/ADempiere/TabManager/index.vue
Labels: bug, (SB) Smart Browser, (WIN) Windows
