Repository solop-develop/frontend-default-theme, pull requests merged in 2023-05, with the labels that each got.

#442 Support VAllocation: initial commit
  components/ADempiere/Form/VAllocation/components/Payments.vue
  components/ADempiere/Form/VAllocation/components/SearchCriteria.vue
  components/ADempiere/Form/VAllocation/components/Summary.vue
  components/ADempiere/Form/VAllocation/components/headersInvoice.js
  components/ADempiere/Form/VAllocation/components/headersPayments.js
  components/ADempiere/Form/VAllocation/index.vue
  components/ADempiere/Form/index.vue
Labels: enhancement, (FRM) Form

#599 Fix: Dashboard Request Redundancy
  components/ADempiere/PanelInfo/index.vue
Labels: bug, dashboard

#600 Muy dificil de leer letra de campos sólo lectura. Está muy clara solo…
  components/ADempiere/FieldDefinition/FieldText.vue
Labels: enhancement, (UX) User Experience

#602 Improve information in Workflow Activities
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/WorkflowManager/WorkflowDiagram.vue
Labels: bug, (WFL) Workflows, (CIO) Code Improvement or Optimization, (UX) User Experience

#603 Support to mobile mode Report and Process
  components/ADempiere/PanelFooter/index.vue
  components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
Labels: (PRC) Processes, (RPT) Reports

#607 Add Icons in Mode Mobile
  components/ADempiere/DataTable/Components/ChangeRecord.vue
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/convenienceButtons/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (UX) User Experience

#610 Fix: Fit Table Payment Allocation
  components/ADempiere/Form/VAllocation/components/Payments.vue
Labels: enhancement, (FRM) Form, (UX) User Experience

#609 Fix: Change Workflow Activities table DImensions
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/WorkflowManager/WorkflowDiagram.vue
Labels: (FRM) Form, (WFL) Workflows, (UX) User Experience

#612 fix: Window chart icons.
  components/ADempiere/PanelInfo/Component/RecordDashboard/component/Parameters.vue
  components/ADempiere/PanelInfo/Component/RecordDashboard/index.vue
Labels: dashboard, (WIN) Windows

#614 Support Tasks
  components/ADempiere/Form/Tasks/executionsList.js
  components/ADempiere/Form/Tasks/headerList.js
  components/ADempiere/Form/Tasks/index.vue
  components/ADempiere/Form/Tasks/summarysList.js
  components/ADempiere/Form/index.vue
Labels: enhancement, (FRM) Form, (PRC) Processes

#615 feat: Change CI/CD GitHub Action.
  .github/workflows/ci.yml
  .github/workflows/docker-image.yml
Labels: enhancement, (CIO) Code Improvement or Optimization

#617 feat: Enable linter and unit test on CI.
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  package.json
  yarn.lock
Labels: enhancement, (CI/CD) Continuous Integration/Continous Delivery

#618 fix: ES Lint on scripts folder.
  .eslintignore
  .github/workflows/ci.yml
  components/ADempiere/Form/Tasks/index.vue
  package.json
  scripts/generate-local-config.js
  scripts/set-new-view-path.js
Labels: bug, (CI/CD) Continuous Integration/Continous Delivery

#619 fix: ES Lint config.
  .eslintrc.js
Labels: bug, (CI/CD) Continuous Integration/Continous Delivery

#620 Fix: Change Language
  components/LangSelect/index.vue
Labels: bug, (TRL) Translation

#622 Support The Matching PO-Receipt-Invoice
  components/ADempiere/Form/VBankStatementMatch/index.vue
  components/ADempiere/Form/VMatch/components/Invoices/index.vue
  components/ADempiere/Form/VMatch/components/Receipt/index.vue
  components/ADempiere/Form/VMatch/components/SearchCriteria/index.vue
  components/ADempiere/Form/VMatch/components/tableFrom.vue
  components/ADempiere/Form/VMatch/index.vue
  components/ADempiere/Form/VMatch/labelTable.js
Labels: enhancement, (FRM) Form

#623 Add new services Payment Print - Export
  components/ADempiere/Form/VPayPrint/index.vue
Labels: enhancement, (FRM) Form

#625 Fix: V-Match
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/Form/VMatch/components/Invoices/index.vue
  components/ADempiere/Form/VMatch/components/SearchCriteria/index.vue
  components/ADempiere/Form/VMatch/index.vue
  components/ADempiere/Form/VMatch/labelTable.js
Labels: enhancement, (FRM) Form

#626 fix: Process without record id.
  components/ADempiere/ModalDialog/index.vue
Labels: bug, (PRC) Processes, (REC) Records, (WIN) Windows

#628 Fix V-Allocation and V-Bank Statement
  components/ADempiere/Form/VAllocation/components/Payments.vue
  components/ADempiere/Form/VAllocation/index.vue
  components/ADempiere/Form/VBankStatementMatch/AutomaticMatch.vue
  components/ADempiere/Form/VBankStatementMatch/ManualMatch.vue
  components/ADempiere/Form/VBankStatementMatch/SearchCriteria.vue
  components/ADempiere/Form/VBankStatementMatch/index.vue
Labels: enhancement, (FRM) Form
