Repository solop-develop/frontend-default-theme, pull requests merged in 2023-01, with the labels that each got.

#439 fix: Tag status on document action.
  components/ADempiere/TabManager/convenienceButtons/documentAction.vue
Labels: (WFL) Workflows, (WIN) Windows

#441 feat: Advanced Query, date field as range.
  components/ADempiere/FieldDefinition/FieldDate.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldRange.js
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (UX) User Experience

#444 feat: Refactor language.
  components/ADempiere/ContainerInfo/workflowLogs.vue
  components/ADempiere/FieldDefinition/FieldDate.vue
  components/ADempiere/FieldDefinition/FieldOptions/ChangeLogs/index.vue
  components/ADempiere/FieldDefinition/FieldOptions/ContextInfo/index.vue
  components/ADempiere/FieldDefinition/FieldOptions/fieldOptionsList.js
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
  components/ADempiere/Form/VPOS/BusinessPartner/businessPartnerUpdate.vue
  components/ADempiere/Form/VPOS/OrderList/FindOrders/index.vue
  components/ADempiere/Form/VPOS/OrderList/index.vue
  components/ADempiere/Form/WorkflowActivity/Guide/steps.js
  components/ADempiere/Form/WorkflowActivity/fieldsList.js
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/PanelInfo/Component/ReferenceRecords/index.vue
  components/ADempiere/TabManager/AdvancedTabQuery.vue
  components/ADempiere/WorkflowManager/WorkflowDiagram.vue
Labels: enhancement, (TRL) Translation, (CIO) Code Improvement or Optimization

#445 fixL Date Translation.
  components/ADempiere/FieldDefinition/FieldDate.vue
Labels: bug, (TRL) Translation, (ULP) UI Lookups

#443 Fix: Align Panel Bar Options
  components/ADempiere/FilterFields/index.vue
Labels: (WIN) Windows, (UX) User Experience

#447 feat: Support Edit Table
  components/ADempiere/DataTable/Components/CellEditInfo.vue
  components/ADempiere/DataTable/Windows/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (UX) User Experience

#450 fix: Display Logic on Tabs.
  components/ADempiere/TabManager/TabLabel.vue
  components/ADempiere/TabManager/tabChild.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#449 Fix: Notification Buttons Does Not Open the Corresponding Tab
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#452 feat: Add fast clear advanced query.
  components/ADempiere/FieldDefinition/FieldYesNo/DefaultTemplate.vue
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#454 feat: List nodes on tab tree.
  components/ADempiere/PanelDefinition/TreePanel.vue
  components/ADempiere/PanelDefinition/index.vue
  components/ADempiere/TabManager/TabPanel.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (UX) User Experience

#453 Fix: Report Does Not Allow Change Export
  components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
Labels: bug, (RPT) Reports

#448 Modify Field Sequence
  components/ADempiere/CollapseCriteria/index.vue
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/PanelDefinition/DraggablePanel.vue
  components/ADempiere/PanelDefinition/SortPanel.vue
  components/ADempiere/PanelDefinition/index.vue
  components/ADempiere/TabManager/TabPanel.vue
Labels: enhancement, (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (UX) User Experience

#455 Fix: Error in the Autocomplete Fields
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#456 Fix: Fields type Select with empty option on list.
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#457 Fix: Just One Scroll
  components/ADempiere/DataTable/Browser/index.vue
  components/ADempiere/TabManager/TabPanel.vue
Labels: bug, (SB) Smart Browser, (WIN) Windows, (UX) User Experience

#458 feat: Clear parameters on report.
  components/ADempiere/ReportManager/Setup/optionsReport.vue
  components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
Labels: enhancement, (PRC) Processes, (UX) User Experience

#459 Fix: Notes button
  components/ADempiere/PanelInfo/Component/RecordNotes/index.vue
  components/ADempiere/TabManager/convenienceButtons/documentStatus.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#465 fix: Eslint with identation.
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: bug, (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#466 feat: Text field clearable.
  components/ADempiere/FieldDefinition/FieldText.vue
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#467 fix: Tab parent bottom border.
  components/ADempiere/TabManager/TabLabel.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#469 feat: Add support to list request on record.
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#468 fix: POS Change Quantity and Discount
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/Form/VPOS/Order/index.vue
  components/ADempiere/Form/VPOS/Order/line/index.vue
Labels: bug, (POS) Point Of Sales, (FRM) Form

#470 Fix: Cache in Accounting field
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
Labels: bug, (FRM) Form, (ULP) UI Lookups, (UX) User Experience

#471 fix: Edit table error on web browser.
  components/ADempiere/DataTable/Components/CellEditInfo.vue
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/FieldDefinition/index.vue
Labels: bug, (REC) Records, (WIN) Windows

#472 feat: Create record on table.
  components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/FieldDefinition/FieldDate.vue
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/mixin/mixinField.js
  components/ADempiere/FieldDefinition/mixin/mixinFieldText.js
  components/ADempiere/TabManager/convenienceButtons/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#474 Support Requests: List Requests associated with a record
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
  components/ADempiere/PanelInfo/index.vue
Labels: enhancement, (WIN) Windows

#463 Fix: Process Workflow
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/WorkflowManager/WorkflowDiagram.vue
Labels: enhancement, (WFL) Workflows

#475 Support Control Panel Activities
  components/ADempiere/HeaderNotification/index.vue
Labels: dashboard

#477 fix: Load tree tab.
  components/ADempiere/PanelDefinition/TreePanel.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#478 fix: Search Field set value with table validation.
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/mixinBusinessPartner.js
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
Labels: bug, (FRM) Form, (ULP) UI Lookups

#480 Add translation to Workflow Diagram
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/HeaderNotification/index.vue
Labels: bug, (WFL) Workflows

#483 feat: Save customization.
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/PanelDefinition/DraggablePanel.vue
  components/ADempiere/PanelDefinition/SortPanel.vue
  components/ADempiere/PanelDefinition/index.vue
Labels: enhancement, (UX) User Experience

#484 Support Customization Level
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/HeaderNotification/index.vue
  components/ADempiere/PanelDefinition/DraggablePanel.vue
Labels: enhancement, (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (UX) User Experience

#489 Fix: Style fixes and adding translations
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
Labels: bug, (FRM) Form, (WIN) Windows

#491 fix: Create new record on table.
  components/ADempiere/DataTable/Windows/index.vue
  components/ADempiere/TabManager/TabPanel.vue
Labels: bug, (REC) Records, (WIN) Windows

#494 Fix: Remove border
  components/ADempiere/Form/Issues/index.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
  components/ADempiere/TabManager/index.vue
Labels: bug, (FRM) Form, (WIN) Windows

#499 fix: Centralize button style.
  components/ADempiere/FieldDefinition/FieldAccountingCombination/tableQueryCriteria.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  components/ADempiere/Form/VPOS/BusinessPartner/businessPartnersList.vue
  components/ADempiere/Form/VPOS/OrderList/index.vue
  components/ADempiere/Form/VPOS/ProductInfo/productList.vue
  components/ADempiere/Form/WorkflowActivity/index.vue
  components/ADempiere/PanelInfo/Component/RecordNotes/index.vue
  components/ADempiere/ReportManager/Setup/optionsReport.vue
  components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug

#500 fix: Displayed value on select field.
  components/ADempiere/FieldDefinition/FieldSelect.vue
Labels: bug, (ULP) UI Lookups

#501 Fix: Open Form Issues
  components/ADempiere/HeaderNotification/index.vue
Labels: (FRM) Form, (WIN) Windows
