Repository solop-develop/frontend-default-theme, pull requests merged in 2023-07, with the labels that each got.

#688 fix: Set selection window table.
  components/ADempiere/DataTable/Windows/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (UX) User Experience

#689 fix: Set selection browser table.
  components/ADempiere/DataTable/Browser/index.vue
  components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (REC) Records, (SB) Smart Browser, (UX) User Experience

#692 fix: Smart Browser, `IN` or `NOT IN` operator with multiple values.
  components/ADempiere/FieldDefinition/FieldOptions/ComparisonOperator.vue
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/index.vue
Labels: bug, (REC) Records, (SB) Smart Browser, (UX) User Experience

#691 Fix: Record Position in the Total Pagination
  components/ADempiere/DataTable/Components/CustomPagination.vue
Labels: (REC) Records, (WIN) Windows, (UX) User Experience

#693 Fix: Switch to Multi Registration with one touch in mobile mode
  components/ADempiere/DataTable/Windows/index.vue
Labels: bug, (REC) Records, (WIN) Windows, (UX) User Experience

#694 Fix: The labels are being displayed on the buttons in the option to delete registration
  components/ADempiere/TabManager/convenienceButtons/DeleteRecordButton.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#696 Fix: Open processes associated with the window in mobile mode
  components/ADempiere/ModalDialog/index.vue
Labels: enhancement, (PRC) Processes, (WIN) Windows, (UX) User Experience

#695 Fix: Movil, menu de acciones, maximo 5 acciones y mas opciones en el drawer
  components/ADempiere/ActionMenu/common-style.scss
  components/ADempiere/ActionMenu/index.vue
  components/ADempiere/ActionMenu/menuMobile.vue
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/TabManager/AdvancedTabQuery.vue
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/TabPanel/modeDesktop.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (PRC) Processes, (REC) Records, (WIN) Windows, (UX) User Experience

#699 fix: Report excel table height.
  components/ADempiere/FileRender/ExcelFile/index.vue
  components/ADempiere/FileRender/HtmlFile/index.vue
Labels: (REC) Records, (RPT) Reports, (UX) User Experience

#702 Fix: Correcting Alignment of Filter fields and action menu
  components/ADempiere/ActionMenu/index.vue
  components/ADempiere/FilterFields/index.vue
Labels: bug, (UX) User Experience

#703 Fix: Open Tab Sequence in Mobile Mode
  components/ADempiere/ActionMenu/menuMobile.vue
  components/ADempiere/PanelDefinition/SortPanel.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#708 fix: Hidden title on button field.
  components/ADempiere/FieldDefinition/index.vue
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#712 Fix: Handle Download
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
Labels: bug, (REC) Records, (WIN) Windows

#713 Fix: V File Import
  components/ADempiere/Form/VFileImport/index.vue
  components/ADempiere/Form/VFileImport/index2.vue
  components/ADempiere/Form/VFileImport/selectTable.vue
  components/ADempiere/Form/VFileImport/uploadFile.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: enhancement, (FRM) Form

#714 fix: Get attachment before upload resource.
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#715 fix: Download attachment.
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
Labels: bug, (WIN) Windows

#716 fix: Attachment eslint.
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
Labels: bug, (CI/CD) Continuous Integration/Continous Delivery, (CIO) Code Improvement or Optimization

#720 feat: Separate `File Import Loader ` form component.
  components/ADempiere/Form/VFileImport/SelectFile/importFormatFields.vue
  components/ADempiere/Form/VFileImport/SelectFile/index.vue
  components/ADempiere/Form/VFileImport/SelectFile/tableRecords.vue
  components/ADempiere/Form/VFileImport/index.vue
  components/ADempiere/Form/VFileImport/selectTable.vue
Labels: enhancement, (FRM) Form

#721 fix remove charset.
  components/ADempiere/Form/VFileImport/selectTable.vue
Labels: bug, (FRM) Form

#722 Fix: Report is launched automatically from Provider tab SDN Window
  components/ADempiere/FieldDefinition/FieldButton.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#723 feat: Attachment visualization.
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
  components/ADempiere/PanelInfo/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#724 feat: `Import File Loader` form, add view attahcment files.
  components/ADempiere/Form/VFileImport/SelectFile/importFormatFields.vue
  components/ADempiere/Form/VFileImport/SelectFile/index.vue
  components/ADempiere/Form/VFileImport/SelectFile/selectResource.vue
  components/ADempiere/Form/VFileImport/SelectFile/tableRecords.vue
Labels: enhancement, (FRM) Form, (UX) User Experience

#725 Fix: Task Manager
  components/ADempiere/Form/TaskManager/index.vue
Labels: bug, (FRM) Form, (UX) User Experience

#726 fix: Client error with upload attachment.
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: bug, (WIN) Windows, (UX) User Experience

#727 fix: Validate upload attachment request.
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: bug, enhancement, (WIN) Windows

#730 Fix: Sort List Options Fields
  components/ADempiere/FieldDefinition/FieldOptions/fieldOptionsList.js
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#731 fix: Field Number format currency.
  components/ADempiere/FieldDefinition/FieldNumber.vue
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#732 fix: Currency format on table.
  components/ADempiere/DataTable/Components/CellDisplayInfo.vue
Labels: bug, (REC) Records, (WIN) Windows, (UX) User Experience

#733 feat: Refactor context utils.
  components/ADempiere/Dashboard/charts/CustomerChart.vue
  components/ADempiere/FieldDefinition/FieldButton.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/index.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/useLocatorWarehouse.js
  components/ADempiere/TabManager/tabChild.vue
Labels: enhancement, (CIO) Code Improvement or Optimization

#734 fix: Report Output without records.
  components/ADempiere/PanelFooter/index.vue
  components/ADempiere/ReportManager/Setup/optionsReport.vue
  components/ADempiere/ReportManager/Setup/optionsReportViewer.vue
Labels: bug, (REC) Records, (RPT) Reports

#735 fix: Report field date is rangue without picker range.
  components/ADempiere/FieldDefinition/FieldDate.vue
Labels: bug, (PRC) Processes, (RPT) Reports, (ULP) UI Lookups

#736 Feat: Support Mode Mobile Attachment
  components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  components/ADempiere/PanelInfo/Component/AttachmentManager/attchment.scss
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/modeDesktop.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/modeMobile.vue
Labels: bug, (WIN) Windows

#737 Feat: Add Description in Header
  components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  components/ADempiere/PanelInfo/Component/AttachmentManager/modeDesktop.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/modeMobile.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: enhancement, (WIN) Windows

#740 Feat: Advanced search as a drawer on Mobile
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#739 Feat: Add Loanding Document Actions
  components/ADempiere/TabManager/convenienceButtons/documentAction.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#743 feat: Add upload attachment as `Image` field.
  components/ADempiere/FieldDefinition/FieldImage.vue
  components/ADempiere/FieldDefinition/mixin/mixinWithDisplayColumn.js
  components/ADempiere/PanelInfo/Component/AttachmentManager/modeMobile.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: enhancement, (ULP) UI Lookups

#746 feat: `Field Image` delete/replace file.
  components/ADempiere/FieldDefinition/FieldImage.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/attachment.js
  components/ADempiere/PanelInfo/Component/AttachmentManager/fileInfo.vue
Labels: enhancement, (REC) Records, (ULP) UI Lookups, (UX) User Experience

#747 feat: `Image` field > Loading preview.
  components/ADempiere/FieldDefinition/FieldImage.vue
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#748 feat: `Field Image` info file.
  components/ADempiere/FieldDefinition/FieldImage.vue
  components/ADempiere/PanelInfo/Component/AttachmentManager/fileInfo.vue
Labels: enhancement, (ULP) UI Lookups, (UX) User Experience

#749 feat: `Field Image` preview on table multi record.
  components/ADempiere/DataTable/Components/CellDisplayInfo.vue
  components/ADempiere/DataTable/Components/CellEditInfo.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (ULP) UI Lookups, (UX) User Experience

#750 feat: `Switch Field` color with `IsActive` column name.
  components/ADempiere/FieldDefinition/FieldYesNo/SwitchTemplate.vue
Labels: enhancement, (WIN) Windows, (ULP) UI Lookups, (UX) User Experience
