Repository solop-develop/frontend-default-theme, pull requests merged in 2023-06, with the labels that each got.

#629 feat: Support to Service Process (Payment Allocation)
  components/ADempiere/Form/VAllocation/components/Payments.vue
  components/ADempiere/Form/VAllocation/components/SearchCriteria.vue
  components/ADempiere/Form/VAllocation/index.vue
Labels: enhancement, (FRM) Form

#631 feat: Issue date format without time.
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/Form/Issues/index.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
Labels: enhancement, (FRM) Form

#630 fix: Fixed header with Issue form
  components/ADempiere/FieldDefinition/FieldText.vue
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/Form/VAllocation/components/Payments.vue
  components/ADempiere/Form/VAllocation/components/SearchCriteria.vue
  components/ADempiere/Form/VAllocation/components/Summary.vue
  components/ADempiere/Form/VAllocation/index.vue
  components/ADempiere/Form/VBankStatementMatch/SearchCriteria.vue
  components/ADempiere/Form/VMatch/components/Invoices/index.vue
  components/ADempiere/Form/VPayPrint/index.vue
Labels: bug, (FRM) Form, (UX) User Experience

#634 Fix: Dashboard Parameters
  components/ADempiere/PanelInfo/Component/RecordDashboard/component/Parameters.vue
Labels: bug, dashboard, (WIN) Windows

#636 Product Finder hides when defining data
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/button.vue
Labels: bug, (ULP) UI Lookups

#639 feat: Change icon process associated on tab when is workflow.
  components/ADempiere/ActionMenu/index.vue
Labels: enhancement, (PRC) Processes, (WFL) Workflows, (WIN) Windows, (UX) User Experience

#641 Fix: Business Partner Search Field not considered in IsoTrx
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
Labels: bug, (REC) Records, (ULP) UI Lookups

#643 Fix: View Existing Workflows for a Document
  components/ADempiere/PanelInfo/index.vue
Labels: bug, (WFL) Workflows, (WIN) Windows

#642 Fix: Validate Operator Null
  components/ADempiere/FieldDefinition/condition/index.vue
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: enhancement, (REC) Records, (WIN) Windows

#644 fix: Amount with currency amount.
  components/ADempiere/FieldDefinition/FieldNumber.vue
Labels: bug, (ULP) UI Lookups

#645 feat: Parameterize `Task Manager` settings.
  components/ADempiere/Form/TaskManager/executionsList.js
  components/ADempiere/Form/TaskManager/headerList.js
  components/ADempiere/Form/TaskManager/index.vue
  components/ADempiere/Form/TaskManager/summarysList.js
  components/ADempiere/Form/Tasks/executionsList.js
  components/ADempiere/Form/Tasks/headerList.js
  components/ADempiere/Form/Tasks/summarysList.js
  components/ADempiere/Form/index.vue
Labels: enhancement, (FRM) Form

#646 feat: Redefine `DocAction` and `DocStatus`.
  components/ADempiere/ContainerOptions/DocumentStatusTag/index.vue
  components/ADempiere/FieldDefinition/FieldOptions/DocumentStatus/index.vue
  components/ADempiere/PanelInfo/Component/workflowLogs/index.vue
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/TabPanel.vue
  components/ADempiere/TabManager/convenienceButtons/documentAction.vue
  components/ADempiere/TabManager/convenienceButtons/documentStatus.vue
  components/ADempiere/TabManager/convenienceButtons/index.vue
  components/ADempiere/TabManager/index.vue
  components/ADempiere/WorkflowManager/WorkflowStatusBar.vue
Labels: enhancement, (WFL) Workflows, (WIN) Windows, (CIO) Code Improvement or Optimization

#647 Fix: Change Window Button Panel Color
  components/ADempiere/DataTable/Components/ChangeRecord.vue
  components/ADempiere/TabManager/convenienceButtons/index.vue
Labels: (WIN) Windows, (UX) User Experience

#648 Fix: Add Quick Field Sequence Option
  components/ADempiere/TabManager/TabLabel.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#651 Fix: Multiple Requests for General Information
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/button.vue
Labels: bug, (ULP) UI Lookups

#653 Fix: Task Manager
  components/ADempiere/Form/TaskManager/index.vue
Labels: bug, (FRM) Form

#652 Fix: Field Text Long
  components/ADempiere/FieldDefinition/FieldTextLong.vue
Labels: bug, (WIN) Windows, (ULP) UI Lookups, (UX) User Experience

#650 feat: Add operators to Smart browsers
  components/ADempiere/FieldDefinition/FieldYesNo/index.vue
  components/ADempiere/FieldDefinition/condition/index.vue
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: enhancement, (REC) Records, (SB) Smart Browser, (ULP) UI Lookups, (UX) User Experience

#655 fix: Tab Document with workflow features and document features.
  components/ADempiere/PanelInfo/index.vue
Labels: bug, (WFL) Workflows, (WIN) Windows

#656 fix: Save line, update parent record.
  components/ADempiere/TabManager/convenienceButtons/index.vue
Labels: bug, (REC) Records, (WIN) Windows

#657 feat: Currency format on Document Lines.
  components/ADempiere/FieldDefinition/FieldNumber.vue
Labels: bug, (WIN) Windows, (ULP) UI Lookups

#660 fix: Advanced Query change conditions on Date values errror.
  components/ADempiere/FieldDefinition/FieldDate.vue
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/FieldDefinition/indexApiComposition.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (WIN) Windows

#661 feat: Mark which operator is currently in the operators list.
  components/ADempiere/FieldDefinition/FieldOptions/ComparisonOperator.vue
  components/ADempiere/FieldDefinition/index.vue
Labels: enhancement, (UX) User Experience

#658 Fix: Print Invoice
  components/ADempiere/ModalDialog/index.vue
Labels: bug, (RPT) Reports, (WIN) Windows

#663 feat: List entities with value type.
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (CIO) Code Improvement or Optimization

#662 feat: `Document Action` panel on Tab Process
  components/ADempiere/FieldDefinition/FieldButton.vue
  components/ADempiere/PanelDefinition/DocumentAction.vue
  components/ADempiere/TabManager/convenienceButtons/documentAction.vue
  components/ADempiere/TabManager/convenienceButtons/nextDocumentAction.vue
Labels: enhancement, (WFL) Workflows, (WIN) Windows

#664 fix: Document Status displayed value on `DocumentAction` panel.
  components/ADempiere/ModalDialog/index.vue
  components/ADempiere/PanelDefinition/DocumentAction.vue
  components/ADempiere/TabManager/convenienceButtons/documentStatus.vue
  components/ADempiere/WorkflowManager/WorkflowStatusBar.vue
Labels: bug, (PRC) Processes, (WFL) Workflows, (WIN) Windows, (UX) User Experience

#665 Fix: Accounting Info
  components/ADempiere/FieldDefinition/FieldButton.vue
  components/ADempiere/FieldDefinition/FieldOptions/LabelField.vue
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/PanelInfo/Component/Accounting/index.vue
  components/ADempiere/PanelInfo/index.vue
  components/ADempiere/TabManager/index.vue
Labels: enhancement, (FRM) Form, (WIN) Windows

#666 fix: Duplicated navigation when search in `Advanced Query`.
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (REC) Records, (WIN) Windows

#667 feat: Improve field `Posted` to accouting info.
  components/ADempiere/PanelInfo/index.vue
Labels: enhancement, (FRM) Form, (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#668 feat: Rename `FieldYesNo` component.
  components/ADempiere/FieldDefinition/FieldYesNo/SelectTemplate.vue
  components/ADempiere/FieldDefinition/FieldYesNo/SwitchTemplate.vue
  components/ADempiere/FieldDefinition/FieldYesNo/index.vue
Labels: enhancement, (ULP) UI Lookups, (CIO) Code Improvement or Optimization

#670 Add Option Exit New sequence
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
Labels: enhancement, (WIN) Windows, (UX) User Experience

#672 fix: Rename field mixin with displayed column.
  components/ADempiere/FieldDefinition/FieldAccountingCombination/mixinAccountingCombination.js
  components/ADempiere/FieldDefinition/FieldAutocomplete.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/index.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  components/ADempiere/FieldDefinition/FieldProductAttribute/index.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/FieldWarehouseLocator/index.vue
  components/ADempiere/FieldDefinition/mixin/mixinWithDisplayColumn.js
Labels: bug, (ULP) UI Lookups

#673 feat: Displayed value on `Button` fields.
  components/ADempiere/FieldDefinition/FieldButton.vue
Labels: enhancement, (REC) Records, (ULP) UI Lookups

#675 Update fieldsDisplayOptions.vue
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
Labels: bug

#676 Refactory Panel Tab Info
  components/ADempiere/PanelInfo/Component/AttachmentManager/index.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
  components/ADempiere/PanelInfo/Component/RecordLogs/index.vue
  components/ADempiere/PanelInfo/Component/RecordNotes/index.vue
  components/ADempiere/PanelInfo/Component/ReferenceRecords/index.vue
  components/ADempiere/PanelInfo/index.vue
Labels: enhancement, (WIN) Windows

#678 Fix: Change Button Style (Cancel and Confirm)
  components/ADempiere/TabManager/convenienceButtons/documentAction.vue
  components/ADempiere/TabManager/convenienceButtons/documentStatus.vue
Labels: enhancement, (UX) User Experience

#680 fix: Change pagination with advanced query filters.
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (REC) Records, (WIN) Windows

#682 feat: Add Copy record on window.
  components/ADempiere/TabManager/convenienceButtons/NewRecordButton.vue
  components/ADempiere/TabManager/convenienceButtons/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (UX) User Experience

#683 feat: Save button with changes.
  components/ADempiere/TabManager/convenienceButtons/DeleteRecordButton.vue
  components/ADempiere/TabManager/convenienceButtons/RefreshRecordButton.vue
  components/ADempiere/TabManager/convenienceButtons/SaveRecordButton.vue
  components/ADempiere/TabManager/convenienceButtons/UndoChangeButton.vue
  components/ADempiere/TabManager/convenienceButtons/index.vue
Labels: enhancement, (REC) Records, (WIN) Windows, (UX) User Experience

#685 fix: Document Action Panel, list without value.
  components/ADempiere/PanelDefinition/DocumentAction.vue
Labels: bug, (UX) User Experience

#687 fix: Mobile field tittle space and crop width name.
  components/ADempiere/FieldDefinition/FieldOptions/LabelField.vue
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
  components/ADempiere/FieldDefinition/index.vue
Labels: bug, (UX) User Experience
