Repository solop-develop/frontend-default-theme, pull requests merged in 2023-03, with the labels that each got.

#550 fix: Field Number set value with enter.
  components/ADempiere/FieldDefinition/FieldNumber.vue
  components/ADempiere/FieldDefinition/older/fieldNumber.js
Labels: bug, (ULP) UI Lookups

#551 feat: Add report type on menu to generate report.
  components/ADempiere/ActionMenu/Actions.vue
  components/ADempiere/FileRender/XmlFile/index.vue
  components/ADempiere/FileRender/downloadFile.vue
Labels: enhancement, (RPT) Reports

#553 fix: Identation es-lint.
  components/ADempiere/Form/VPOS/OrderList/index.vue
Labels: bug, (POS) Point Of Sales, (FRM) Form

#554 perf: Remove old process run code.
  components/ADempiere/Form/ProductInfo/productList.vue
  components/ADempiere/Form/VPOS/Options/index.vue
Labels: enhancement, (CIO) Code Improvement or Optimization

#555 fix: Field list as field text.
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/FieldSelectMultiple.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#556 fix: Infinity loop on country field of location form.
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/mixinLocationAddress.js
  components/ADempiere/FieldDefinition/FieldSelect.vue
  components/ADempiere/FieldDefinition/mixin/mixinFieldSelect.js
Labels: bug, (ULP) UI Lookups

#557 fix: Multiple context info field.
  components/ADempiere/FieldDefinition/FieldOptions/ContextInfo/index.vue
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
Labels: bug, (ULP) UI Lookups, (UX) User Experience

#558 fix: Zoom reference window.
  components/ADempiere/ActionMenu/Actions.vue
  components/ADempiere/ActionMenu/References.vue
  components/ADempiere/ActionMenu/Relations.vue
  components/ADempiere/ActionMenu/common-style.scss
  components/ADempiere/ActionMenu/index.vue
  components/ADempiere/PanelInfo/Component/ReferenceRecords/index.vue
  components/ADempiere/TabManager/index.vue
Labels: bug, (REC) Records, (WIN) Windows

#559 perf: Remove deprecated reference manager.
  components/ADempiere/TabManager/TabOptions.vue
  components/ADempiere/TabManager/TabPanel.vue
  components/ADempiere/TabManager/index.vue
  components/ADempiere/TabManager/tabChild.vue
Labels: enhancement, (CIO) Code Improvement or Optimization

#561 fix: Field Business Partner Search clear query criteria.
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/businessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/BusinessPartnerInfo/buttonBusinessPartnersList.vue
  components/ADempiere/FieldDefinition/FieldSearch/GeneralInfoSearch/panel.vue
  components/ADempiere/FieldDefinition/FieldSearch/mixinFieldSearch.js
  components/ADempiere/Form/VPOS/BusinessPartner/businessPartnersList.vue
Labels: bug, (ULP) UI Lookups

#560 Fix: Show Sequence
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
Labels: (PRC) Processes, (RPT) Reports, (SB) Smart Browser, (WIN) Windows, (ULP) UI Lookups

#562 fix: Country without region displayed region field if is capture sequ…
  components/ADempiere/FieldDefinition/FieldLocationAddress/index.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/mixinLocationAddress.js
Labels: bug, (ULP) UI Lookups

#563 fix: Field Location Address with mandatory on capture sequence.
  components/ADempiere/FieldDefinition/FieldLocationAddress/index.vue
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
Labels: enhancement, (ULP) UI Lookups

#564 feat: Allow cities out of list.
  components/ADempiere/FieldDefinition/FieldLocationAddress/fieldsList.js
  components/ADempiere/FieldDefinition/FieldLocationAddress/locationAddressForm.vue
  components/ADempiere/FieldDefinition/FieldOptions/index.vue
Labels: enhancement, (ULP) UI Lookups

#569 feat: Time Record remove unused code.
  components/ADempiere/Form/TimeRecord/createForm.vue
Labels: enhancement, (FRM) Form, (CIO) Code Improvement or Optimization

#571 fix: Request notifications after logout.
  components/ADempiere/HeaderNotification/index.vue
Labels: bug, (SE) Security

#572 fix: Change css class into fields.
  components/ADempiere/FieldDefinition/FieldAutocomplete.vue
  components/ADempiere/FieldDefinition/FieldBinary.vue
  components/ADempiere/FieldDefinition/FieldDate.vue
  components/ADempiere/FieldDefinition/FieldImage.vue
  components/ADempiere/FieldDefinition/FieldText.vue
  components/ADempiere/FieldDefinition/FieldTextLong.vue
  components/ADempiere/FieldDefinition/FieldTime.vue
  components/ADempiere/FieldDefinition/FieldUrl.vue
  components/ADempiere/FieldDefinition/FieldYesNo/AdvancedQueryTemplate.vue
  components/ADempiere/FieldDefinition/FieldYesNo/DefaultTemplate.vue
  components/ADempiere/FieldDefinition/index.vue
  components/ADempiere/FieldDefinition/indexApiComposition.vue
Labels: enhancement, (CIO) Code Improvement or Optimization

#573 fix: Filter fields.
  components/ADempiere/FilterFields/fieldsDisplayOptions.vue
  components/ADempiere/FilterFields/index.vue
  components/ADempiere/PanelDefinition/DraggablePanel.vue
  components/ADempiere/PanelDefinition/StandardPanel.vue
  components/ADempiere/PanelDefinition/index.vue
Labels: bug, (PRC) Processes, (RPT) Reports, (SB) Smart Browser

#574 feat: Add record time on issues.
  components/ADempiere/Form/Issues/component/Comment.vue
  components/ADempiere/Form/Issues/index.vue
  components/ADempiere/Form/Issues/recordTime.vue
  components/ADempiere/Form/TimeRecord/createForm.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/component/Comment.vue
  components/ADempiere/PanelInfo/Component/RecordIssues/index.vue
Labels: enhancement, (FRM) Form

#576 feat: Support attachment with JWT.
  components/ADempiere/PanelInfo/Component/AttachmentManager/uploadResource.vue
Labels: enhancement, (WIN) Windows, (SE) Security

#577 Fixed: Show Registry filter in window pane mode
  components/ADempiere/TabManager/TabPanel.vue
Labels: bug, (WIN) Windows

#578 Fix: Error on Advanced Search and list field
  components/ADempiere/TabManager/AdvancedTabQuery.vue
Labels: bug, (REC) Records, (WIN) Windows
